services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    networks:
      - net
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
